[dev]
  functions = "netlify/functions/"
  functionsPort = 9000
  autoLaunch = false
[build]
  command = "npm run build"
  functions = "lambda"
  publish = ".next"

[functions]
  directory = "netlify/functions"
