[dev]
  functions = "netlify/functions/"
  functionsPort = 9000
  autoLaunch = false
[build]
  command = "npm run build"
  functions = "lambda"
  publish = "build"
  node_bundler = "esbuild"

[functions]
  directory = "netlify/functions"

[[plugins]]
  package = "@netlify/plugin-functions-install-core"