[dev]
  functions = "netlify/functions/"
  functionsPort = 9000
[build]
  command = "npm run build"
  functions = "lambda"
  publish = "build"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
